# Generated by Django 4.2.6 on 2023-12-08 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('number_verificate', models.IntegerField(blank=True)),
                ('type_account', models.CharField(max_length=20)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_card', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=16, unique=True)),
                ('validity', models.DateField(blank=True)),
                ('cvv', models.IntegerField(blank=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_card_credit', to='Kebank.account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='Kebank/images/%Y/%m/%d/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('born_date', models.DateField()),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_movimentation', models.CharField(choices=[('Pix', 'Pix'), ('Pix cartão de crédito', 'Pix cartão crédito'), ('Empréstimo', 'Empréstimo')], max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_movimentation', to='Kebank.creditcard')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_from_account', to='Kebank.account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_to_account', to='Kebank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_solicitation', models.DateTimeField(auto_now_add=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('date_approved', models.DateField(auto_now_add=True)),
                ('requested_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('approved', models.BooleanField(blank=True)),
                ('installment_quantity', models.IntegerField()),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kebank.account')),
            ],
        ),
        migrations.CreateModel(
            name='JuridicPerson',
            fields=[
                ('state_registration', models.CharField(max_length=11)),
                ('open_date', models.DateField()),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_type', models.CharField(max_length=30)),
                ('rentability', models.CharField(blank=True, max_length=20)),
                ('date_closure', models.CharField(max_length=10)),
                ('administration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='Kebank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_card', models.CharField(default='Mastercard', max_length=20)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('validity', models.DateField()),
                ('cvv', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_card', to='Kebank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('federative_unit', models.CharField(max_length=2)),
                ('pac', models.CharField(max_length=10)),
                ('public_place', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('juridic_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_address_JuridicPerson', to='Kebank.juridicperson')),
                ('physical_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_person_address_LegalPerson', to='Kebank.physicalperson')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='juridic_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_JuridicPerson', to='Kebank.juridicperson'),
        ),
        migrations.AddField(
            model_name='account',
            name='physical_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_LegalPerson', to='Kebank.physicalperson'),
        ),
    ]
