# Generated by Django 4.2.6 on 2023-11-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
