# Generated by Django 4.2.6 on 2023-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0002_loan_installment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
